name: DartExamplets
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: dford <email@example.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  quiver: ^2.1.2+1

dev_dependencies:
  test: ^1.6.1
